### ISSUE TITLE
Setup repo

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#1]
- NodeJS + TypeScript
- eslint + prettier
- CI checks using GitHub Action
- `docker-compose.yaml` for spinning up local dev environment.
    - Postgres

**Comment by Arthelon** [comment]
TypeScript boilerplate I'm using is setup to use [StandardJS](https://standardjs.com/) (built on ESLint) for linting and formatting.

**Comment by kiootic** [comment]
Can you help to check if it covers all the rules in our preset (https://github.com/oursky/eslint-oursky), or is there some substantial differences?

**Comment by Arthelon** [comment]
I see a mix of similarities and differences when comparing these two:
- https://github.com/oursky/eslint-oursky/blob/master/src/configs/typescript.js
- https://github.com/standard/eslint-config-standard-with-typescript/blob/master/src/index.ts

I can switch to eslint/prettier setup if you want

**Comment by kiootic** [comment]
I see StandardJS is... rather different to what most of our developers prefers, especially on 'no semicolon' rule.

Do you have any preference? If not, I think it's better to stick to our preset (https://github.com/oursky/eslint-oursky).

**Comment by Arthelon** [comment]
no preference. I will switch to your presets.
