### ISSUE TITLE
Process commit data and add to postgres

### ISSUE THREAD

**Issue by Arthelon** [oursky/gitlint-bot#16]
After linting the commit messages from a Push Webhook event, create Postgres records for each commit and commit diagnosis. 

If a `User` record for the commit's committer doesn't exist, then create a new record.

**Comment by Arthelon** [comment]
@kiootic The `User` record should be the user who committed the commit instead of the author right?

**Comment by kiootic** [comment]
We should use commit author.

For reference: https://stackoverflow.com/questions/18750808/difference-between-author-and-committer-in-git
