### ISSUE TITLE
Duplicate Users in staging DB

### ISSUE THREAD

**Issue by Arthelon** [oursky/gitlint-bot#29]
In the staging db, there are some duplicate User `email` and `name` records. 

I believe this issue is caused by the async execution of the list of `saveCommit` promises in `src/listeners.ts`.

Might also want to add a unique constraint on the `email`, `name` columns.

**Comment by Arthelon** [comment]
Was able to duplicate the bug on development environment after increasing the network latency of local containers.

**Comment by kiootic** [comment]
May I know what's your planned solution to fix the issue?

**Comment by Arthelon** [comment]
Issue is fixed by having the promises execute sequentially. 

I need to write some SQL to clean up the duplicate data, should I include this in the repo?

**Comment by kiootic** [comment]
> Issue is fixed by having the promises execute sequentially. I also want to add a unique constraint on user email/name columns so that this throws an error in the future.

I agree with this fix. Another thing to note is that it's better to run the each save commit action in a transaction, to ensure each save is atomic.

> I need to write some SQL or use Knex to clean up the duplicate data, should I include this in the repo?

This is a data migration, so you can create a new migration for this. I suppose the migration should:
- clean up the duplicated data; and
- setup unique constraints.
