### ISSUE TITLE
Improve notification message

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#35]
Currently, the notification message is like:
```
In the past 7 days, there were a total of 8 analyzed commits with 0 rule violations
```

There is insufficient detail to be useful. We should include more information to make it useful to the users.

**Comment by Arthelon** [comment]
I'm thinking of splitting the summary message into the following different sections: 
- Top 5 lint rules with the highest total scores
    - Show rule name, and # of rule violations
- Top 10 repositories with the highest total scores
   - Show name of repo with hyperlink, total number of rule violations, and sublist of top 5 rules with the highest scores for that repo
         - sublist of rules shows rule name, and # of rule violations
- Top 10 users with the highest total scores
   - name of user, total number of rule violations, sublist of top 5 rules with highest scores for user

**Comment by kiootic** [comment]
Some suggestions:
- showing the lint rules without a context (repo, commit, etc.) would not be useful, since the commit message often originated from the 'culture' of a specific project.
- 10 repositories/users would be too much, people would not like an overly long message in the channel.
- Displaying user name directly would be like putting blames on them; we'd like to provide data on commit message quality and how to improve, not to put blame on people.
- I would suggest showing the top 10 (with tie-breaker) commit messages (with links to the commit for context), so that we can see the general characteristics of the messages.

**Comment by Arthelon** [comment]
I like the idea of displaying the top 10 commits directly. I think there will be a lot of ties starting off, bc of how few rules we have, but this should improve after adding more. 

I agree that 10 repositories/users is too much but I still want to include information related to the repositories. What do you think about including the top 5 repositories with a small list of lint rules that were most frequently violated in addition to the top 10 commits section?

**Comment by kiootic** [comment]
> I agree that 10 repositories/users is too much but I still want to include information related to the repositories. What do you think about including the top 5 repositories with a small list of lint rules that were most frequently violated in addition to the top 10 commits section?

Sure, 5 repositories seems good to me.

**Comment by Arthelon** [comment]
The summary message right now is pretty long. Do you think we should still include repository-specific info?

**Comment by kiootic** [comment]
Let's only keep these information for each commit to keep the message short:
- repo name, commit hash, and link to commit
- number of rule violations
- commit message subject line

Also, let's show just the top 5 commits for now to see if the message is readable enough.

**Comment by Arthelon** [comment]
> Let's only keep these information for each commit to keep the message short:
> 
> * repo name, commit hash, and link to commit
> * number of rule violations
> * commit message subject line
> 
> Also, let's show just the top 5 commits for now to see if the message is readable enough.

My bad, I was referencing the separate "Top 5 Repositories with highest scores" section that we talked about including in addition to the Top 10 commits with highest scores

**Comment by kiootic** [comment]
I think the commit information at the moment seems useful enough, let's put showing the top repos on hold.

**Comment by kiootic** [comment]
Some suggestions to reduce visual clutters:
- Remove total score on commit
- Move the commit message to same line as commit hash
- Remove rule score and use normal text (instead of code block), since all rules have same score for now.
