### ISSUE TITLE
CLI tool

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#57]
We should have a CLI tool that developers can run locally to produce same diagnosis (as in the bot) using configuration file.

**Comment by Arthelon** [comment]
Proposed CLI usage: 

```
Usage: gitlint-cli [options]

  Git commit message linter

Options:
--help, -h.       displays this help message
--config, -c     path to config file
--from, -f.        lower end of commit range to lint
--to, -t.            upper end of commit range to lint
--quiet, q.       suppresses console output

**Comment by kiootic** [comment]
Some notes from our discussion:
- A subcommand to generate pre-commit hooks
- A subcommand to scaffold the configuration
- Publish as a NPM package for developer's consumption

**Comment by Arthelon** [comment]
Some of the previous issues with the build had to do with the `@gitlint-bot/lint` package being private. This package should be made public along with `@gitlint-bot/cli`.
