### ISSUE TITLE
[Web UI] List of analyzed commits

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#59]
- List of all analyzed commits
    - TODO: fields to display in list page
- With pagination
- Links to detail page of the commit
    - Occurred errors during commit analysis
    - TODO: fields to display in detail page

**Comment by Arthelon** [comment]
@kiootic do you think it makes sense to only show commits with violations?

**Comment by kiootic** [comment]
Sure, that's seems fine. Most users would just care about the violations anyways.

**Comment by kiootic** [comment]
@Arthelon if you got some time left, please also update the slack message with links to the commit detail page.
