### ISSUE TITLE
[Web UI] Tracking issue

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#61]
A simple web UI to display information that cannot fit within the weekly Slack message.

A frontend framework/good visual design is not required, but clean HTML with correct semantics is preferred. Server-side rendered pages with templates are acceptable.

- [x] Authentication (#60)
- [x] Dashboard (#58)
- [x] Commit list (#59)

**Comment by Arthelon** [comment]
I estimate all of these issues should take 2-3 days to finish.

**Comment by kiootic** [comment]
Can you give a more detailed breakdown of estimated time of each task? Usually we would limit each task to use at most 1 day, and break them down if it takes more than a day to finish it.

**Comment by Arthelon** [comment]
Estimated time for tasks:
- Auth
    - Auth backend setup with Passport (2 hours)
    - Decide on template-engine and setup server-side rendering (30 mins)
    - Web interface for signing in (1 hour)
- Summary Dashboard
    - Brainstorm designs for per-repo summary (30 mins)
    - API endpoints and SQL queries (30 mins - 1 hr)
    - Web interface for dashboard (2-4 hours)
- List of analyzed commits
    - API Endpoints and SQL queries for pagination and detailed commit page (30 mins - 1 hr)
    - UI for paginated commit list (1-2 hours)
    - UI for detailed commits page (1-2 hours)

**Comment by kiootic** [comment]
Can you describe on what kind of auth method (e.g. username & password, GItHub,Google, etc.) you're planning to use?

**Comment by Arthelon** [comment]
Google OAuth2
