### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by kiootic** [oursky/gitlint-bot#7]
- Choose a ORM/query builder/use raw SQL
- Schema (ER diagram)
    - in README
    - can use [MermaidJS](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgQVtDaHJpc3RtYXNdIC0tPnxHZXQgbW9uZXl8IEIoR28gc2hvcHBpbmcpXG4gIEIgLS0-IEN7TGV0IG1lIHRoaW5rfVxuICBDIC0tPnxPbmV8IERbTGFwdG9wXVxuICBDIC0tPnxUd298IEVbaVBob25lXVxuICBDIC0tPnxUaHJlZXwgRltmYTpmYS1jYXIgQ2FyXVxuXHRcdCIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)
- Migrations

**Comment by Arthelon** [comment]
I will try to using [Knex.js](http://knexjs.org/) as the query builder
